---

- name: scan facts with raw_windows_setup
  raw_windows_setup:

- name: debug ansible_powershell_version (2/2)
  ansible.builtin.debug:
    msg: "ansible_powershell_version: {{ ansible_powershell_version }}"
