---

- name: scan facts with raw_windows_setup
  raw_windows_setup:

- name: debug ansible_kernel
  ansible.builtin.debug:
    msg: "ansible_kernel: {{ ansible_kernel }}"

- name: debug ansible_distribution_major_version
  ansible.builtin.debug:
    msg: "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"

- name: debug ansible_powershell_version (1/2)
  ansible.builtin.debug:
    msg: "ansible_powershell_version: {{ ansible_powershell_version }}"

- name: debug powershell target version
  ansible.builtin.debug:
    msg: "target powershell version: {{ powershell_target_version }}"
